name: 'server_universe_project'
description: 'Serve Universal Library For Help you make server rest api on cross platform support edge functions Supabase, Vercel, Netlify, cloud Flare and more'
version: '0.0.0'
repository: 'https://github.com/azkadev/server_universe'
homepage: 'https://github.com/azkadev/server_universe'
issue_tracker: 'https://github.com/azkadev/server_universe/issues'
documentation: 'https://github.com/azkadev/server_universe/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.2.3'
dependencies: 
  alfred: ^1.1.1
  general_lib: '^0.0.34'
  mason_logger: '^0.2.11'
  packagex: '^0.0.50'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: '^3.1.2'
  yaml_edit: '^2.2.0'
  yaml_writer: '^2.0.0'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
