name: 'server_universe_dart_http_client'
description: 'Serve Universal Library For Help you make server rest api on cross platform support edge functions Supabase, Vercel, Netlify, cloud Flare and more'
homepage: 'https://github.com/azkadev/server_universe'
repository: 'https://github.com/azkadev/server_universe'
version: '0.0.1'
issue_tracker: 'https://github.com/azkadev/server_universe/issues'
documentation: 'https://github.com/azkadev/server_universe/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  server_universe_dart: '^0.0.1'
  http: '^1.1.0'
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.16.0'
