name: 'example'
description: 'A sample command-line application.'
version: '1.0.0'
environment: 
  sdk: '^3.3.3'
dependencies: 
  server_universe: '^0.0.10'
  server_universe_http_client: 'any'
  general_lib: '^0.0.34'
dependency_overrides: 
  pointycastle: '3.8.0'
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
homepage: 'https://github.com/azkadev/server_universe'
repository: 'https://github.com/azkadev/server_universe'
issue_tracker: 'https://github.com/azkadev/server_universe/issues'
documentation: 'https://github.com/azkadev/server_universe/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
server_universe: 
  supabase: 
    input_file: 'bin/example_supabase.dart'
    output_directory: 'supabase/functions/example'
