name: 'server_universe_dart'
description: 'Server Universe Library For Help you make server rest api on cross platform support edge functions Supabase, Vercel, Netlify, cloud Flare and more'
homepage: 'https://github.com/azkadev/server_universe'
repository: 'https://github.com/azkadev/server_universe'
version: '0.0.13'
issue_tracker: 'https://github.com/azkadev/server_universe/issues'
documentation: 'https://github.com/azkadev/server_universe/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics: 
  - 'server'
  - 'socket'
  - 'api'
  - 'backend'
  - 'network'
environment: 
  sdk: '>3.2.0 <4.0.0'
dependencies: 
  server_universe: '^0.0.13'
dependency_overrides: 
  pointycastle: '3.8.0'
dev_dependencies: 
  build_runner: '^2.3.3'
  freezed: '^2.3.2'
  lints: '^3.0.0'
  test: '^1.16.0'
  shelf: '^1.4.0'
  shelf_router: '^1.1.3'
executables: 
  server_universe_dart: 'server_universe_dart'
