name: 'server_universe_dart'
description: 'Serve Universal Library For Help you make server rest api on cross platform support edge functions Supabase, Vercel, Netlify, cloud Flare and more'
homepage: 'https://github.com/azkadev/server_universe'
repository: 'https://github.com/azkadev/server_universe'
version: '0.0.0'
publish_to: 'none'
issue_tracker: 'https://github.com/azkadev/server_universe/issues'
documentation: 'https://github.com/azkadev/server_universe/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
  
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>3.1.0 <4.0.0'
dependencies: 
  freezed_annotation: '^2.2.0'
  js: '^0.6.7'
  typings: '^0.0.6+2'
  mime: '^1.0.5'
  mime_type: '^1.0.0'
  queue: '^3.1.0'
  meta: '^1.14.0'
  path: '^1.9.0'
  general_lib: '^0.0.34'
  mason_logger: '^0.2.11'
  collection: '^1.18.0'
  yaml: '^3.1.2'
  yaml_writer: '^2.0.0'
  server_universe_scheme: 
    path: '../server_universe_scheme'

dependency_overrides: 
  general_lib: 
    path: '../../../general_project/library/general_lib'  
dev_dependencies: 
  build_runner: '^2.3.3'
  freezed: '^2.3.2'
  lints: '^3.0.0'
  test: '^1.16.0'
  shelf: '^1.4.0'
  shelf_router: '^1.1.3'
  http: '^1.1.0'
executables: 
  server_universe_dart: 'server_universe_dart'
