name: 'server_universe_scheme'
description: 'Serve Universal Library For Help you make server rest api on cross platform support edge functions Supabase, Vercel, Netlify, cloud Flare and more'
version: '0.0.1'
repository: 'https://github.com/azkadev/server_universe'
homepage: 'https://github.com/azkadev/server_universe'
issue_tracker: 'https://github.com/azkadev/server_universe/issues'
documentation: 'https://github.com/azkadev/server_universe/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.3.0'
dependencies: 
  path: '^1.9.0'
  general_lib: '^0.0.35'
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
