name: 'server_universe'
description: 'Server Universe Library For Help you make server rest api on cross platform support edge functions Supabase, Vercel, Netlify, cloud Flare and more'
repository: 'https://github.com/azkadev/server_universe'
homepage: 'https://youtube.com/@azkadev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
version: '0.0.38'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics:
  - 'server'
  - 'socket'
  - 'api'
  - 'backend'
  - 'network'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  mime: '^2.0.0'
  path: '^1.9.0'
  general_lib: '^0.0.70'
  collection: '^1.19.0'
  yaml: '^3.1.3'
  http: '^1.3.0'
  web: '^1.1.1'
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
dev_dependencies:
  build_runner: '^2.3.3'
  lints: '^5.0.0'
  test: 'any'
executables:
  server_universe: 'server_universe'
screenshots:
  - description: 'Server Universe Logo'
    path: 'assets/server_universe.png'
project:
  type: ''
