name: 'server_universe'
description: 'Server Universe Library For Help you make server rest api on cross platform support edge functions Supabase, Vercel, Netlify, cloud Flare and more'
homepage: 'https://github.com/azkadev/server_universe'
repository: 'https://github.com/azkadev/server_universe'
version: '0.0.36'
issue_tracker: 'https://github.com/azkadev/server_universe/issues'
documentation: 'https://github.com/azkadev/server_universe/tree/main/docs'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics:
  - 'server'
  - 'socket'
  - 'api'
  - 'backend'
  - 'network'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  js: '^0.7.1'
  typings_fork: '^0.0.7'
  mime: '^2.0.0'
  meta: '>=1.11.0 <=1.16.0'
  path: '^1.9.0'
  general_lib: '^0.0.63'
  collection: '^1.19.0'
  yaml: '^3.1.3'
  http: '^1.2.2'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
dev_dependencies:
  build_runner: '^2.3.3'
  lints: '^5.0.0'
  test: 'any'
executables:
  server_universe: 'server_universe'
screenshots:
  - description: 'Server Universe Logo'
    path: 'assets/server_universe.png'
